import { Navigation } from "@/components/Navigation/navigation";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IvoryIT Front-Chapter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <h1>IvoryIT Front-Chapter</h1>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
